import {
    WX_ALL_SUBPACKAGES,
    WX_API_BASE_DOMAIN,
    WX_CITY_BANNER_CASUAL_BLOCK_URL,
    WX_PRELOAD_SUBPACKAGES,
    WX_REMOTE_LOAD_DIRECTORY,
    WX_REMOTE_SERVER_ROOT,
    WX_REMOTE_SETTINGS_FILE_URL,
    WX_SELF_SERVER_APP_ID,
    WX_REMOTE_SUBPACKAGES
} from "./platforms/WechatConfig";
import {
    OPPO_ALL_SUBPACKAGES,
    OPPO_API_BASE_DOMAIN,
    OPPO_CITY_BANNER_CASUAL_BLOCK_URL,
    OPPO_PRELOAD_SUBPACKAGES,
    OPPO_REMOTE_LOAD_DIRECTORY,
    OPPO_REMOTE_SERVER_ROOT,
    OPPO_REMOTE_SETTINGS_FILE_URL,
    OPPO_SELF_SERVER_APP_ID
} from "./platforms/OppoConfig";

export const VERSION = '1.2.6';
// export const VERSION = 'dev';
// export const IS_DEBUG = true;
export const IS_DEBUG = false;

export const SAVE_DATA_KEY = "gameData_dinosaur";  //本地存储游戏数据时使用的存储key

let _API_BASE_DOMAIN = 'https://gamedata.sy3.com/api';  //api服务端接口的基地址
let _REMOTE_SERVER_ROOT = 'https://cdn.birdfly.sy3.com/dinosaur/v1.0.1/';  //远程CDN基地址
let _REMOTE_LOAD_DIRECTORY = [     //远程加载目录
];
let _REMOTE_SETTINGS_FILE_URL = 'https://cdn.birdfly.sy3.com/dinosaur/webSettings_wx.json';  //远程开关文件URL
let _CITY_BANNER_CASUAL_BLOCK_URL = 'https://mergefarm.sy3.com/city-block.php'; //城市屏蔽接口地址
let _SELF_SERVER_APP_ID = 5; //自有服务器游戏Id
let _ALL_SUBPACKAGES = []; //所有的分包
let _PRELOAD_SUBPACKAGES = []; //需要预读的分包
let _REMOTE_SUBPACKAGES = {}

    _API_BASE_DOMAIN = WX_API_BASE_DOMAIN;
    _REMOTE_SERVER_ROOT = WX_REMOTE_SERVER_ROOT;
    _REMOTE_LOAD_DIRECTORY = WX_REMOTE_LOAD_DIRECTORY;
    _REMOTE_SETTINGS_FILE_URL = WX_REMOTE_SETTINGS_FILE_URL;
    _CITY_BANNER_CASUAL_BLOCK_URL = WX_CITY_BANNER_CASUAL_BLOCK_URL;
    _SELF_SERVER_APP_ID = WX_SELF_SERVER_APP_ID;
    _ALL_SUBPACKAGES = WX_ALL_SUBPACKAGES;
    _PRELOAD_SUBPACKAGES = WX_PRELOAD_SUBPACKAGES;
    _REMOTE_SUBPACKAGES = WX_REMOTE_SUBPACKAGES

//api服务端接口的基地址
export const API_BASE_DOMAIN = _API_BASE_DOMAIN;
export const REMOTE_SERVER_ROOT = _REMOTE_SERVER_ROOT;
export const REMOTE_LOAD_DIRECTORY = _REMOTE_LOAD_DIRECTORY;
export const REMOTE_SETTINGS_FILE_URL = _REMOTE_SETTINGS_FILE_URL;
export const CITY_BANNER_CASUAL_BLOCK_URL = _CITY_BANNER_CASUAL_BLOCK_URL;
export const SELF_SERVER_APP_ID = _SELF_SERVER_APP_ID;
export const ALL_SUBPACKAGES = _ALL_SUBPACKAGES;
export const PRELOAD_SUBPACKAGES = _PRELOAD_SUBPACKAGES;
export const REMOTE_SUBPACKAGES = _REMOTE_SUBPACKAGES;

