export module UIConfig{

    export let MAIN_VIEW='MainView'
    export let COMPLETE_VIEW='CompletedView'
    export let TOP_VIEW='TopView'
    export let BATTLE_VIEW='BattleView'
    export let GM_VIEW='GMView'
    export let SIGN_VIEW='SignView'
    export let OFFLINE_VIEW='OfflineView'
    export let TIPS_VIEW='TipsView'
    export let LOGIN_VIEW='LoginView'
    export let GIFT_VIEW='GiftView'
    export let GUIDE_TIP_VIEW='GuideTipView'
    export let UPDATE_TIPS_VIEW='UpdateTipsView'
    export let CHAPTER_VIEW='ChapterView'
    export let SHOUCANG_VIEW='ShouCangView'
    export let RANK_VIEW='RankView'
    export let WHEEL_VIEW='WheelView'
    export let GET_ITEM_VIEW='GetItemView'
    export let GET_SURPRISE_VIEW='GetSurpriseView'
    export let AD_CLOSE_VIEW='ADCloseView'
    export let STAGE_END_VIEW='StageEndView'
    export let WARN_VIEW='WarnView'
    export let GUIDE_VIEW='GuideView'

    export let EFFECT_FADE='fade'
    export let EFFECT_POP='pop'    
}